#!/usr/bin/env php
<?php

require __DIR__
    . DIRECTORY_SEPARATOR
    . '..'
    . DIRECTORY_SEPARATOR
    . 'vendor'
    . DIRECTORY_SEPARATOR
    . 'autoload.php'
;

use Cekurte\Resume\Command\CreateCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new CreateCommand());
$application->run();