#!/usr/bin/env php
<?php

require realpath(__DIR__ . '/../bootstrap.php');
require VENDOR_PATH . DS . 'autoload.php';

use Jpcercal\Resume\Command\ResumeCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->setName('Resume');
$application->setVersion('v1.1');
$application->add(new ResumeCommand());
$application->run();
