name: Resume

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - run: |
          npm install
      
      - run: |
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
          path: resume.pdf

      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add resume.pdf
          git add resume-preview.pdf.png
          git add resume-preview.json.png
          git commit --amend --no-edit

      - uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          force_with_lease: true

      - uses: actions/github-script@v7
        if: github.ref == 'refs/heads/main'
        with:
          script: |       
            const fs = require('fs').promises;

            const padding = (v) => v < 10 ? `0${v}` : v;

            const date = new Date();
            const year = padding(date.getFullYear());
            const month = padding(date.getMonth());
            const day = padding(date.getDate());
            const hours = padding(date.getHours());
            const minutes = padding(date.getMinutes());
            const seconds = padding(date.getSeconds());

            const major = year - 2023;
            const minor = month;
            const patch = `${day}${hours}${minutes}${seconds}`;

            const releaseName = `${major}.${minor}.${patch}`;

            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${releaseName}`,
              sha: context.sha
            });

            const createReleaseResponse = await github.rest.repos.createRelease({
              draft: false,
              generate_release_notes: true,
              name: releaseName,
              owner: context.repo.owner,
              prerelease: false,
              repo: context.repo.repo,
              tag_name: releaseName,
            });

            await github.rest.repos.uploadReleaseAsset({
              name: 'resume.pdf',
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: createReleaseResponse.data.id,
              data: await fs.readFile('./resume.pdf')
            });

            return releaseName;
